#pragma kernel GenerateNoise

struct SmallHash
{
    uint primeA;
    uint primeB;
    uint primeC;
    uint primeD;
    uint primeE;
    
    uint accumulator;

    uint BytesA() { return accumulator & 255;}
    uint BytesD() { return accumulator >> 24;}
    
    double Floats01A() { return (double)BytesA() * (1.0 / 255.0);}
    double Floats01D() { return (double)BytesD() * (1.0 / 255.0);}

    SmallHash Add(SmallHash h, int v)
    {
        h.accumulator += v;
        return h;
    }

    uint ToUInt(SmallHash hash)
    {
        uint avalanche = hash.accumulator;
        avalanche ^= avalanche >> 15;
        avalanche *= primeB;
        avalanche ^= avalanche >> 13;
        avalanche *= primeC;
        avalanche ^= avalanche >> 16;
        return avalanche;
    }

    SmallHash Eat(SmallHash h, int data)
    {
        h.accumulator = RotateLeft(accumulator + (uint)data * primeC, 17) * primeD;
        return h;
    }

    uint RotateLeft(uint data, int steps)
    {
        return (data << steps) | (data >> 32 - steps);
    }
};


static const int numThreads = 8;

AppendStructuredBuffer<float4> noiseAndPos;
RWStructuredBuffer<float3> noisePositions;
RWStructuredBuffer<float3> positions;


int numPointsPerAxis;
int seed;
int frequency;
int octaves;
int lacunarity;
float persistence;

int test = 0;

int IndexFromCoord(int x, int y, int z) 
{
    return z * numPointsPerAxis * numPointsPerAxis + y * numPointsPerAxis + x;
}
 
struct LatticeSpan
{
    int p0, p1;
    double g0, g1;
    double t;
};


LatticeSpan GetLatticeSpan(double coordinates, int frequency)
{
    coordinates *= frequency;
    double points = floor(coordinates);
    LatticeSpan span;
    span.p0 = (int)points;
    span.p1 = span.p0 + 1;
    span.g0 = coordinates - span.p0;
    span.g1 = span.g0 - 1.0;
    span.t = coordinates - points;
    span.t = span.t * span.t * span.t * (span.t * (span.t * 6.0 - 15.0) + 10.0);
    return span;
}

double PerlinEvaluate(SmallHash hash, double x, double y, double z)
{
    double gx = hash.Floats01A() * 2.0 - 1.0;
    double gy = hash.Floats01D() * 2.0 - 1.0;
    double gz = 1.0 - abs(gx) - abs(gy);
    double offset = max(-gz, 0.0);
    gx += gx < 0.0 ? offset : -offset;
    gy += gy < 0.0 ? offset : -offset;
    return (gx * x + gy * y + gz * z) / 0.56290;
}

double GetNoise(float3 noisePosition, SmallHash hash, int frequency)
{
    LatticeSpan x = GetLatticeSpan(noisePosition.x, frequency);
    LatticeSpan y = GetLatticeSpan(noisePosition.y, frequency);
    LatticeSpan z = GetLatticeSpan(noisePosition.z, frequency);

    SmallHash h0 = hash.Eat(hash, x.p0);
    SmallHash h1 = hash.Eat(hash, x.p1);

    SmallHash h00 = h0.Eat(h0, y.p0);
    SmallHash h01 = h0.Eat(h0, y.p1);
    SmallHash h10 = h1.Eat(h1, y.p0);
    SmallHash h11 = h1.Eat(h1, y.p1);

    double L00 = lerp(PerlinEvaluate(h00.Eat(h00, z.p0), x.g0, y.g0, z.g0), PerlinEvaluate(h00.Eat(h00, z.p1), x.g0, y.g0, z.g1), z.t);
    double L01 = lerp(PerlinEvaluate(h01.Eat(h01, z.p0), x.g0, y.g1, z.g0), PerlinEvaluate(h01.Eat(h01, z.p1), x.g0, y.g1, z.g1), z.t);
			
    double L0 = lerp(L00, L01, y.t);
			
    double L10 = lerp(PerlinEvaluate(h10.Eat(h10, z.p0), x.g1, y.g0, z.g0), PerlinEvaluate(h10.Eat(h10, z.p1), x.g1, y.g0, z.g1), z.t);
    double L11 = lerp(PerlinEvaluate(h11.Eat(h11, z.p0), x.g1, y.g1, z.g0), PerlinEvaluate(h11.Eat(h11, z.p1), x.g1, y.g1, z.g1), z.t);
			
    double L1 = lerp(L10, L11, y.t);

    return lerp(L0, L1, x.t);
}

[numthreads(numThreads,1,1)]
void GenerateNoise(int3 id : SV_DispatchThreadID)
{
    int i = IndexFromCoord(id.x, id.y, id.z);
    
    SmallHash hash;
    hash.primeA = 0x9E3779B1;
    hash.primeB = 0x85EBCA77;
    hash.primeC = 0xC2B2AE3D;
    hash.primeD = 0x27D4EB2F;
    hash.primeE = 0x165667B1;
    hash.accumulator = seed + hash.primeE;
    
    int freq = frequency;
    float amplitude = 1.0;
    float amplitudeSum = 0.0;
    double noiseSum = 0.0;
    
    for(int j=0; j < octaves; j++)
    {
        noiseSum += GetNoise(noisePositions[i], hash.Add(hash, j), frequency) * amplitude;
        amplitudeSum += amplitude;
        freq *= lacunarity;
        amplitude *= persistence;
    }

    //value = numPointsPerAxis;

    float4 value = float4(positions[i], noiseSum / amplitudeSum / 2 + 0.5);
    noiseAndPos.Append(value);
}
