#pragma kernel March

#include "MarchTables.compute"
#include "NoiseCompute.compute"

static const int numThreads = 8;

struct DrawVertex {
    float3 worldPosition;
};

struct DrawTriangle {
    DrawVertex vertices[3];
};

AppendStructuredBuffer<DrawTriangle> DrawTriangles;


struct IndirectArgs {
    uint numVerticesPerInstance;
    uint numInstances;
    uint startVertexIndex;
    uint startInstanceIndex;
};

RWStructuredBuffer<IndirectArgs> IndirectArgsBuffer;


////////////////////////////////////////////////////////////////////////////////////////////////
//OLD
////////////////////////////////////////////////////////////////////////////////////////////////

float isoLevel;

float3 interpolateVerts(float4 v1, float4 v2)
{
    float t = (isoLevel - v1.w) / (v2.w - v1.w);
    return v1.xyz + t * (v2.xyz-v1.xyz);
}

int indexFromCoord(int x, int y, int z) 
{
    return z * (dimensions.x + 1) * (dimensions.y + 1) + y * (dimensions.z + 1) + x;
}

[numthreads(numThreads,numThreads,numThreads)]
void March (int3 id : SV_DispatchThreadID)
{   
    // Stop one point before the end because voxel includes neighbouring points
    if (id.x >= dimensions.x || id.y >= dimensions.y || id.z >= dimensions.z) 
    {
        return;
    }

    if(id.x == 0 && id.y == 0 && id.z == 0)
    {
        DrawTriangle tri;
        DrawVertex origin;
        origin.worldPosition = float3(0, 0, 0);
        tri.vertices[0] = origin;
        tri.vertices[1] = origin;
        tri.vertices[2] = origin;

        DrawTriangles.Append(tri);

        InterlockedAdd(IndirectArgsBuffer[0].numVerticesPerInstance, 3);
    }

    // 8 corners of the current cube
    float4 cubeCorners[8] = 
    {
        GenerateNoise(id),
        GenerateNoise(int3(id.x + 1, id.y, id.z)),
        GenerateNoise(int3(id.x + 1, id.y, id.z + 1)),
        GenerateNoise(int3(id.x, id.y, id.z + 1)),
        GenerateNoise(int3(id.x, id.y + 1, id.z)),
        GenerateNoise(int3(id.x + 1, id.y + 1, id.z)),
        GenerateNoise(int3(id.x + 1, id.y + 1, id.z + 1)),
        GenerateNoise(int3(id.x, id.y + 1, id.z + 1))
    };

    // Calculate unique index for each cube configuration.
    // There are 256 possible values
    // A value of 0 means cube is entirely inside surface; 255 entirely outside.
    // The value is used to look up the edge table, which indicates which edges of the cube are cut by the isosurface.
    int cubeIndex = 0;
    if (cubeCorners[0].w < isoLevel) cubeIndex |= 1;
    if (cubeCorners[1].w < isoLevel) cubeIndex |= 2;
    if (cubeCorners[2].w < isoLevel) cubeIndex |= 4;
    if (cubeCorners[3].w < isoLevel) cubeIndex |= 8;
    if (cubeCorners[4].w < isoLevel) cubeIndex |= 16;
    if (cubeCorners[5].w < isoLevel) cubeIndex |= 32;
    if (cubeCorners[6].w < isoLevel) cubeIndex |= 64;
    if (cubeCorners[7].w < isoLevel) cubeIndex |= 128;

    // Create triangles for current cube configuration
    for (int i = 0; triangulation[cubeIndex][i] != -1; i +=3) 
    {
        // Get indices of corner points A and B for each of the three edges
        // of the cube that need to be joined to form the triangle.
        int a0 = cornerIndexAFromEdge[triangulation[cubeIndex][i]];
        int b0 = cornerIndexBFromEdge[triangulation[cubeIndex][i]];

        int a1 = cornerIndexAFromEdge[triangulation[cubeIndex][i+1]];
        int b1 = cornerIndexBFromEdge[triangulation[cubeIndex][i+1]];

        int a2 = cornerIndexAFromEdge[triangulation[cubeIndex][i+2]];
        int b2 = cornerIndexBFromEdge[triangulation[cubeIndex][i+2]];

        DrawTriangle tri;

        DrawVertex vertA;
        vertA.worldPosition = interpolateVerts(cubeCorners[a0], cubeCorners[b0]);

        DrawVertex vertB;
        vertB.worldPosition = interpolateVerts(cubeCorners[a1], cubeCorners[b1]);

        DrawVertex vertC;
        vertC.worldPosition = interpolateVerts(cubeCorners[a2], cubeCorners[b2]);

        tri.vertices[0] = vertA;
        tri.vertices[1] = vertB;
        tri.vertices[2] = vertC;
        
        DrawTriangles.Append(tri);

        InterlockedAdd(IndirectArgsBuffer[0].numVerticesPerInstance, 3);
    }
}
