#include "MarchingCubes.compute"

// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel GenerateChunks

struct DrawMesh
{
    float3 vertices[];
    float3 triangles[];
};

struct  DrawChunk
{
    float3 position;
    float3 localPosition;

    DrawMesh mesh;
};

float3 worldOrigin;


DrawChunk CreateChunk(int3 coord)
{
    DrawChunk chunk;
    chunk.localPosition = float3(coord.x * 10 - (dimensions.x / 2 - 10 / 2), coord.y * 10 - (dimensions.y / 2 - 10 / 2), coord.z * 10 - (dimensions.z / 2 - 10 / 2));
    chunk.position = worldOrigin + chunk.localPosition;
    
    return chunk;
}

[numthreads(8,8,8)]
void GenerateChunks (uint3 id : SV_DispatchThreadID)
{
    
}
