#pragma kernel March

#include "./MarchTables.compute"
#include "./NoiseCompute.compute"

static const int numThreads = 8;

struct Vertex
{
    float3 position;
    float3 normal;
};

struct Triangle
{
    Vertex vertices[3];
};


AppendStructuredBuffer<Triangle> _DrawTriangles;

RWStructuredBuffer<uint> _RenderArgs;

float _IsoLevel;

float3 interpolateVerts(float4 v1, float4 v2)
{
    float t = (_IsoLevel - v1.w) / (v2.w - v1.w);
    return v1.xyz + t * (v2.xyz-v1.xyz);
}

int indexFromCoord(int x, int y, int z) 
{
    return z * (_ChunkSize.x + 1) * (_ChunkSize.y + 1) + y * (_ChunkSize.z + 1) + x;
}

float3 CalculateTriangleNormal(float3 a, float3 b, float3 c) {
    return normalize(cross(b - a, c - a));
}

[numthreads(numThreads,numThreads,numThreads)]
void March (int3 id : SV_DispatchThreadID)
{   
    if (id.x >= _ChunkSize.x || id.y >= _ChunkSize.y || id.z >= _ChunkSize.z) 
    {
        return;
    }
    
    float4 cubeCorners[8] = 
    {
        GenerateNoise(id),
        GenerateNoise(int3(id.x + 1, id.y, id.z)),
        GenerateNoise(int3(id.x + 1, id.y, id.z + 1)),
        GenerateNoise(int3(id.x, id.y, id.z + 1)),
        GenerateNoise(int3(id.x, id.y + 1, id.z)),
        GenerateNoise(int3(id.x + 1, id.y + 1, id.z)),
        GenerateNoise(int3(id.x + 1, id.y + 1, id.z + 1)),
        GenerateNoise(int3(id.x, id.y + 1, id.z + 1))
    };
    
    int cubeIndex = 0;
    if (cubeCorners[0].w < _IsoLevel) cubeIndex |= 1;
    if (cubeCorners[1].w < _IsoLevel) cubeIndex |= 2;
    if (cubeCorners[2].w < _IsoLevel) cubeIndex |= 4;
    if (cubeCorners[3].w < _IsoLevel) cubeIndex |= 8;
    if (cubeCorners[4].w < _IsoLevel) cubeIndex |= 16;
    if (cubeCorners[5].w < _IsoLevel) cubeIndex |= 32;
    if (cubeCorners[6].w < _IsoLevel) cubeIndex |= 64;
    if (cubeCorners[7].w < _IsoLevel) cubeIndex |= 128;
    
    for (int i = 0; triangulation[cubeIndex][i] != -1; i +=3) 
    {
        int a0 = cornerIndexAFromEdge[triangulation[cubeIndex][i]];
        int b0 = cornerIndexBFromEdge[triangulation[cubeIndex][i]];

        int a1 = cornerIndexAFromEdge[triangulation[cubeIndex][i+1]];
        int b1 = cornerIndexBFromEdge[triangulation[cubeIndex][i+1]];

        int a2 = cornerIndexAFromEdge[triangulation[cubeIndex][i+2]];
        int b2 = cornerIndexBFromEdge[triangulation[cubeIndex][i+2]];


        Vertex vertexA;
        Vertex vertexB;
        Vertex vertexC;
        
        vertexA.position = interpolateVerts(cubeCorners[a0], cubeCorners[b0]);
        
        vertexB.position = interpolateVerts(cubeCorners[a1], cubeCorners[b1]);
        
        vertexC.position = interpolateVerts(cubeCorners[a2], cubeCorners[b2]);
        
        float3 triNormal = CalculateTriangleNormal(vertexC.position, vertexB.position, vertexA.position);
        
        vertexA.normal = triNormal;
        vertexB.normal = triNormal;
        vertexC.normal = triNormal;

        Triangle tri;
        
        tri.vertices[2] = vertexA;
        tri.vertices[1] = vertexB;
        tri.vertices[0] = vertexC;
        
        _DrawTriangles.Append(tri);

        InterlockedAdd(_RenderArgs[0], 3);
    }
}
