#include "HashCompute.compute"

int _Seed;
int _Frequency;
int _Octaves;
int _Lacunarity;
float _Persistence;

bool applyFallOff;
float _Steepness;
float _CenterSize;

float4 _ChunkSize;
float4 _Dimensions;

float4 _IndexOffset;
float4 _LocalChunkPos;

struct LatticeSpan
{
    int p0, p1;
    float g0, g1;
    float t;
};

float FallOffEvaluate(float value)
{
    return pow(abs(value), _Steepness) / (pow(abs(value), _Steepness) + pow(abs(_CenterSize - _CenterSize * value), _Steepness));
}

float GetFallOffValue(float3 pos)
{
    if (!applyFallOff)
        return 0.0;

    float3 samplePos = pos.xyz + _LocalChunkPos;

    float x = samplePos.x / _Dimensions.x * 2.0;
    float y = samplePos.y / _Dimensions.y * 2.0;
    float z = samplePos.z / _Dimensions.z * 2.0;

    float val1 = max(abs(x), abs(y));
    float val2 = max(val1, abs(z));

    return FallOffEvaluate(val2);
}

float3 GetPosition(int3 index)
{
    return float3( index.x - _ChunkSize.x / 2, index.y - _ChunkSize.y / 2, index.z - _ChunkSize.z / 2);
}

float3 GetNoisePosition(int3 index)
{
    return (_IndexOffset.xyz + GetPosition(index)) / 1000.0f;
}

LatticeSpan GetLatticeSpan(float coordinates, int frequency)
{
    coordinates *= frequency;
    const float points = floor(coordinates);
    LatticeSpan span;  
    span.p0 = (int)points;
    span.p1 = span.p0 + 1;
    span.g0 = coordinates - span.p0;
    span.g1 = span.g0 - 1.0;
    span.t = coordinates - points;
    span.t = span.t * span.t * span.t * (span.t * (span.t * 6.0 - 15.0) + 10.0);
    return span;
}

float PerlinEvaluate(SmallHash hash, float x, float y, float z)
{
    float gx = hash.Floats01A() * 2.0 - 1.0;
    float gy = hash.Floats01D() * 2.0 - 1.0;
    float gz = 1.0 - abs(gx) - abs(gy);
    float offset = max(-gz, 0.0);
    gx += gx < 0.0 ? offset : -offset;
    gy += gy < 0.0 ? offset : -offset;
    return (gx * x + gy * y + gz * z) / 0.56290;
}

float GetNoise(float3 noisePosition, SmallHash hash, int frequency)
{
    LatticeSpan x = GetLatticeSpan(noisePosition.x, frequency);
    LatticeSpan y = GetLatticeSpan(noisePosition.y, frequency);
    LatticeSpan z = GetLatticeSpan(noisePosition.z, frequency);

    SmallHash h0 = hash.Eat(hash, x.p0);
    SmallHash h1 = hash.Eat(hash, x.p1);

    SmallHash h00 = h0.Eat(h0, y.p0);
    SmallHash h01 = h0.Eat(h0, y.p1);
    SmallHash h10 = h1.Eat(h1, y.p0);
    SmallHash h11 = h1.Eat(h1, y.p1);

    float L00 = lerp(PerlinEvaluate(h00.Eat(h00, z.p0), x.g0, y.g0, z.g0), PerlinEvaluate(h00.Eat(h00, z.p1), x.g0, y.g0, z.g1), z.t);
    float L01 = lerp(PerlinEvaluate(h01.Eat(h01, z.p0), x.g0, y.g1, z.g0), PerlinEvaluate(h01.Eat(h01, z.p1), x.g0, y.g1, z.g1), z.t);

    float L0 = lerp(L00, L01, y.t);

    float L10 = lerp(PerlinEvaluate(h10.Eat(h10, z.p0), x.g1, y.g0, z.g0), PerlinEvaluate(h10.Eat(h10, z.p1), x.g1, y.g0, z.g1), z.t);
    float L11 = lerp(PerlinEvaluate(h11.Eat(h11, z.p0), x.g1, y.g1, z.g0), PerlinEvaluate(h11.Eat(h11, z.p1), x.g1, y.g1, z.g1), z.t);

    float L1 = lerp(L10, L11, y.t);

    return lerp(L0, L1, x.t);
}

float4 GenerateNoise(int3 id)
{
    SmallHash hash;
    hash.primeA = 0x9E3779B1;
    hash.primeB = 0x85EBCA77;
    hash.primeC = 0xC2B2AE3D;
    hash.primeD = 0x27D4EB2F;
    hash.primeE = 0x165667B1;
    hash.accumulator = _Seed + hash.primeE;

    int freq = _Frequency;
    float amplitude = 1.0;
    float amplitudeSum = 0.0;
    float noiseSum = 0.0;

    float3 noisePos = GetNoisePosition(id);
    float3 pos = GetPosition(id);

    for (int j = 0; j < _Octaves; j++)
    {
        noiseSum += GetNoise(noisePos, hash.Add(hash, j), freq) * amplitude;
        amplitudeSum += amplitude;
        freq *= _Lacunarity;
        amplitude *= _Persistence;
    }

    float val = (noiseSum / amplitudeSum / 2 + 0.5) - GetFallOffValue(pos);

    return float4(pos, val);
}
